name: Ora2PG Docker CI

on:
  push:
    branches:
      - '*'       # Matches any branch
      - '*/*'     # matches every branch containing a single '/'
      - '**'      # matches every branch
    paths:
      - 'ora2pg/**'
      - '.github/**/postgres-db-ora2pg.yml'

env:
  APPLICATION_NAME: postgres-db-migration
  APPLICATION_ARTIFACTID: postgres-ora2pg
  APPLICATION_VERSION: 2022.1.0 ##0.1.37

jobs:
  build:
    runs-on: ubuntu-latest
    ##  run: docker build . --file Dockerfile --tag ora2pg
    steps:
    - name: Update Version
      run: |
        echo "APPLICATION_VERSION=${{env.APPLICATION_VERSION}}-$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Update Image Tag
      run: |
        echo "APPLICATION_IMAGE_TAG=${{ env.APPLICATION_NAME }}:$APPLICATION_VERSION" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    - name: Build and publish Docker Image  - ${{ env.APPLICATION_VERSION }}
      run: |
        docker build -t $APPLICATION_IMAGE_TAG -f ora2pg/Dockerfile .